// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@1.0.0";

// src/lib/mcp/tools/list-knowledge-topics.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@1.0.0";
var TOPICS = {
  visual: {
    title: "Visual Impairment Accommodations",
    summary: "Visual impairments range from low vision to total blindness. With the right assistive technology and workplace adjustments, visually impaired employees thrive in nearly every role.",
    accommodations: [
      "Screen reader software (NVDA, JAWS, VoiceOver)",
      "Screen magnification tools (ZoomText, built-in OS magnifiers)",
      "High-contrast displays and adjustable font sizes",
      "Braille displays and embossers",
      "Accessible document formats (tagged PDFs, semantic HTML)"
    ],
    tips: [
      "Ensure all digital content meets WCAG 2.1 AA standards",
      "Provide orientation and mobility training for the office",
      "Use descriptive alt text on every image and chart",
      "Keep walkways clear and consistently arranged"
    ]
  },
  hearing: {
    title: "Hearing Accessibility Solutions",
    summary: "Deaf and hard-of-hearing employees benefit most from clear communication channels and visual equivalents of audio information.",
    accommodations: [
      "Qualified sign language interpreters",
      "Real-time captioning (CART) for meetings and events",
      "Video relay services and captioned phones",
      "Visual fire alarms and notification systems",
      "Noise-reducing workstations and FM/loop systems"
    ],
    tips: [
      "Always face the person when speaking",
      "Caption every internal and external video",
      "Share agendas and notes in writing before meetings",
      "Use chat tools alongside voice calls"
    ]
  },
  mobility: {
    title: "Mobility Support Strategies",
    summary: "Mobility disabilities cover a wide range of conditions affecting movement. Physical and procedural adjustments unlock full participation.",
    accommodations: [
      "Step-free access, ramps, and automatic doors",
      "Height-adjustable desks and ergonomic seating",
      "Accessible restrooms within reasonable distance",
      "Reserved accessible parking close to entrances",
      "Remote and hybrid work options"
    ],
    tips: [
      "Audit your office annually against accessibility standards",
      "Keep aisles at least 36 inches wide",
      "Offer flexible scheduling for medical appointments",
      "Provide voice-control or alternative input devices"
    ]
  },
  cognitive: {
    title: "Cognitive Disability Support",
    summary: "Cognitive disabilities affect memory, attention, problem-solving, or processing speed. Structure and clarity make a major difference.",
    accommodations: [
      "Written instructions and visual checklists",
      "Task-management apps and reminder tools",
      "Quiet workspaces with minimal interruptions",
      "Extended deadlines or modified workloads where reasonable",
      "Job coaching and mentoring support"
    ],
    tips: [
      "Break large projects into clear, sequential steps",
      "Confirm understanding by asking the employee to summarize",
      "Use plain language and avoid idioms",
      "Schedule regular, predictable check-ins"
    ]
  },
  neurodiversity: {
    title: "Neurodiversity in the Workplace",
    summary: "Neurodivergent employees \u2014 including autistic, ADHD, and dyslexic people \u2014 bring unique strengths when environments respect different ways of thinking.",
    accommodations: [
      "Sensory-friendly lighting and noise-cancelling headphones",
      "Flexible communication (written vs. verbal)",
      "Predictable routines with advance notice of changes",
      "Quiet rooms for sensory regulation",
      "Clear, literal task descriptions and expectations"
    ],
    tips: [
      "Avoid surprise meetings \u2014 share agendas ahead of time",
      "Allow stimming, movement, and fidget tools",
      "Focus on outcomes, not on social conformity",
      "Offer multiple ways to contribute (writing, recording, presenting)"
    ]
  },
  universal: {
    title: "Universal Design Principles",
    summary: "Universal Design creates environments and products usable by everyone, regardless of ability \u2014 reducing the need for individual accommodations.",
    accommodations: [
      "Step-free entrances used by all employees",
      "Captions on every video benefit everyone in noisy environments",
      "Adjustable furniture suits every body type",
      "Plain-language documents help all readers",
      "Multiple input methods (keyboard, mouse, voice, touch)"
    ],
    tips: [
      "Design for the edges and the middle benefits",
      "Involve disabled employees in the design process",
      "Test products with diverse users early and often",
      "Treat accessibility as a quality standard, not a checklist"
    ]
  }
};
var list_knowledge_topics_default = defineTool({
  name: "list_knowledge_topics",
  title: "List knowledge topics",
  description: "List the disability and inclusion topics in the PLUSME knowledge base (visual, hearing, mobility, cognitive, neurodiversity, universal design).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const topics = Object.entries(TOPICS).map(([id, t]) => ({ id, title: t.title, summary: t.summary }));
    return {
      content: [{ type: "text", text: JSON.stringify(topics, null, 2) }],
      structuredContent: { topics }
    };
  }
});

// src/lib/mcp/tools/get-accommodation-guide.ts
import { defineTool as defineTool2, ToolError } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z } from "npm:zod@^3.25.76";
var get_accommodation_guide_default = defineTool2({
  name: "get_accommodation_guide",
  title: "Get accommodation guide",
  description: "Get the PLUSME accommodation guide for one disability topic: overview, recommended accommodations, and practical workplace tips. Call list_knowledge_topics first to see the valid topic ids.",
  inputSchema: {
    topic: z.string().min(1).describe("Topic id: visual, hearing, mobility, cognitive, neurodiversity, or universal.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ topic }) => {
    const guide = TOPICS[topic.trim().toLowerCase()];
    if (!guide) {
      throw new ToolError(
        `Unknown topic "${topic}". Valid topics: ${Object.keys(TOPICS).join(", ")}.`
      );
    }
    const result = { topic: topic.trim().toLowerCase(), ...guide };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@1.0.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-profile.ts
var get_my_profile_default = defineTool3({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Read the signed-in PLUSME user's profile (display name and avatar).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("display_name, avatar_url, created_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: "No profile found for this user yet." }],
        structuredContent: { profile: null }
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/update-my-profile.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@1.0.0";
import { z as z2 } from "npm:zod@^3.25.76";
var update_my_profile_default = defineTool4({
  name: "update_my_profile",
  title: "Update my profile",
  description: "Update the signed-in PLUSME user's display name and/or avatar URL.",
  inputSchema: {
    display_name: z2.string().trim().min(1).optional().describe("New display name."),
    avatar_url: z2.string().trim().url().optional().describe("New avatar image URL.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true },
  handler: async ({ display_name, avatar_url }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (display_name === void 0 && avatar_url === void 0) {
      return {
        content: [{ type: "text", text: "Provide display_name and/or avatar_url to update." }],
        isError: true
      };
    }
    const updates = {};
    if (display_name !== void 0) updates.display_name = display_name;
    if (avatar_url !== void 0) updates.avatar_url = avatar_url;
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").update(updates).eq("user_id", ctx.getUserId()).select("display_name, avatar_url");
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: `Profile updated: ${JSON.stringify(data?.[0] ?? updates)}` }],
      structuredContent: { profile: data?.[0] ?? updates }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "duezeqilajlyekhdzodh";
var mcp_default = defineMcp({
  name: "plusme",
  title: "Plusme",
  version: "0.1.0",
  instructions: "PLUSME is a workplace inclusion platform. Use list_knowledge_topics to browse disability inclusion topics, get_accommodation_guide for detailed workplace accommodations per topic, and get_my_profile / update_my_profile to read or update the signed-in user's profile.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_knowledge_topics_default, get_accommodation_guide_default, get_my_profile_default, update_my_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@1.0.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
